
name: Deploy DotNet project to Azure Function App

on: 
  workflow_dispatch:
    inputs:
      AZURE_FUNCTIONAPP_NAME:
        description: 'Define env name'     
        required: true

env:
  AZURE_FUNCTIONAPP_NAME: ${{github.event.inputs.AZURE_FUNCTIONAPP_NAME}}   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')

jobs:
  build-and-deploy:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh # For Linux, use bash
      run: |
        pushd '${{ github.workspace }}/${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: publish test results
      uses: actions/upload-artifact@v1
      with:
            name: report
            path: output\${{ env.AZURE_FUNCTIONAPP_NAME }}.dll
      

   
